Ignore NoSuchMethodError
Using reflection method is visible.

Refs #4


(This commit was moved from https://github.com/3D-e-Chem/knime-testflow. Original id: 3760985c36e476475113f2fe6778c3cfc6fcdbac)