Make more noise when NoSuchMethodError occurs
(This commit was moved from https://github.com/3D-e-Chem/knime-testflow. Original id: ffed396bf0bb7bcc264f9e3e076892526464ccb1)